### ISSUE TITLE
aeson-qq-0.8.0 fails to build

### ISSUE THREAD

**Issue by elanakoren** [zalora/aeson-qq#14]
Hi,

We've been trying to parse JSON with hspec-JSON-wai. Cabal installing hspec-JSON-wai fails because of a broken dependency on aeson-qq-0.8.0. We can't directly install aeson-qq-0.8.0 either:

```
±  |master ✗| → cabal install aeson-qq
Resolving dependencies...
Notice: installing into a sandbox located at
/Users/workspace/haskelltest/.cabal-sandbox
Configuring aeson-qq-0.8.0...
Building aeson-qq-0.8.0...
Failed to install aeson-qq-0.8.0
Last 10 lines of the build log ( /Users/workspace/haskelltest/.cabal-sandbox/logs/aeson-qq-0.8.0.log ):
Building aeson-qq-0.8.0...
Preprocessing library aeson-qq-0.8.0...
[1 of 2] Compiling Data.JSON.QQ     ( src/Data/JSON/QQ.hs, dist/dist-sandbox-b17efec7/build/Data/JSON/QQ.o )

src/Data/JSON/QQ.hs:79:49: Not in scope: ‘A.scientific’
cabal: Error: some packages failed to install:
aeson-qq-0.8.0 failed during the building phase. The exception was:
ExitFailure 1
```

Aeson-qq-0.7.0 installs fine.

**Comment by sol** [comment]
Hi, thanks for reporting this.  Can you please add the output of `cabal exec ghc-pkg list`.

**Comment by ericTsiliacos** [comment]
Hi @sol, I was pairing with Elana when we discovered this and after further investigation, we had discovered that we were using an old version of the cabal library and cabal tools. Once we used the latest Haskell Platform, we were able to install aeson-qq successfully. This issue can be closed. Thanks!

**Comment by sol** [comment]
The Haskell platform is not what most Haskell developers use, and I generally don't recommend it. Most people use GHC and the latest version of cabal-install, and install everything else from Hackage.
